# Generated by Django 4.1 on 2022-09-01 12:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('number', models.IntegerField(unique=True)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NOT-TO-SAY', "Don't want to say")], default='Choose one', max_length=20)),
                ('path', models.CharField(choices=[('ENG', 'Engineering'), ('SS', 'Social Sciences'), ('ART', 'Arts'), ('OTHER', 'Others')], default='Choose one', max_length=20)),
            ],
        ),
    ]
