# Generated by Django 4.1 on 2022-09-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NOT-TO-SAY', "Don't want to say")], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='path',
            field=models.CharField(choices=[('ENG', 'Engineering'), ('SS', 'Social Sciences'), ('ART', 'Arts'), ('OTHER', 'Others')], max_length=20),
        ),
    ]
