# Generated by Django 4.1 on 2022-09-09 01:23

import builtins
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0005_alter_student_email_alter_student_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=builtins.id),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
