# Generated by Django 4.1 on 2022-09-09 15:21

import builtins
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0007_alter_student_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=builtins.id),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=builtins.id),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.IntegerField(unique=builtins.id),
        ),
    ]
